name: xeus-kernels
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - conda-forge
dependencies:
  # xeus-python
  #- xeus-python
  #- ipycanvas
  # other packages including octave
  - xeus
  - xeus-lite
  - nlohmann_json
  - nlohmann_json-abi
  - octave
  - libpng
  - zlib
  - libflang
  - pcre2
  - libblas
  - liblapack
  - freetype
  - plotly
  # R package
  #- xeus-r
