name: xeus-kernels
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  # Xeus-Octave
  - cmake
  - make
  - pkg-config
  - emscripten_emscripten-wasm32==3.1.73
  # JupyterLite
  - jupyterlite-core
  - jupyter_server
  - jupyterlite-xeus
  # xeus-python
  - xeus-python
  - ipycanvas
  # other packages including octave
  - xeus
  - xeus-lite
  - nlohmann_json
  - nlohmann_json-abi
  - octave
  - libpng
  - zlib
  - libflang
  - pcre2
  - libblas
  - liblapack
  - freetype
  - plotly
