name: xeus-kernels
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - conda-forge
dependencies:
  - xeus
  - xeus-lite
  - xeus-python
  - ipycanvas
  - numpy
  - matplotlib
  - xeus-r
  - nlohmann_json
  - nlohmann_json-abi
  - octave
  - libpng
  - zlib
  - libflang
  - pcre2
  - libblas
  - liblapack
  - freetype
  - plotly
  - oct2py
